<?
$PERM["paccount_seller"]["8"]="R";
$PERM["paccount_seller"]["7"]="R";
$PERM["paccount_seller"]["*"]="D";
$PERM["paccount_buyer"]["8"]="R";
$PERM["paccount_buyer"]["6"]="R";
$PERM["paccount_buyer"]["*"]="D";
$PERM["/"]["8"]="W";
$PERM["/"]["*"]="R";
$PERM["index.php"]["G5"]="W";
$PERM["index.php"]["G8"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
?>